### ISSUE TITLE
[feature request] Info shown on Wallet

### ISSUE THREAD

**Issue by n00d1e5** [clawfire/covid19-passbook-generator#104]
### Describe the solution you'd like

Currently, some people just check the certificat with the information shown on the it.
It means that they do not even use the scanner app to verify the QR Code.
Hence, in my opinion, the information shown on the wallet (between name and QR Code) should be more related to that propose.

Today, the information shown are: birthday, unique certificate identifier and certificate type.
If you can update to: birthday (compare with ID), date de vaccination (check if more than 14 days), dose (ex. 2/2), type (of vaccination) and vaccination name.
All the other information keep in the details which will be shown by clicking the three-point button.

You can add your LU certificat to French AntiCovid app, they just display necessary info.

By the way, if you can remove the word "Show this when requested" under the QR Code, that could be much better. The description here is not mandatory for a wallet card.

### Anything else?

For example:

[EU Digital COVID Certificate] [Country]
LU

[SURENAMES & FORENAMES]
Handsome Clawfire

[DATE OF BIRTH] [TYPE OF VACCINATION]
01/01/1999                                  Vaccination

[VACCINATION NAME*] [DOSE] [DATE]
BioNTech                       2/2       30/07/2021

*The name can be replaced with "Product"

**Comment by clawfire** [comment]
Hey @n00d1e5,  thanks for the feature request.

In fact, all those information ARE already in the back of the wallet card. You cannot access it through the quick double power button press on iPhone, you have to open the wallet app, then you can display the back of the card. Just as the EU asked their state member to create an on-phone digital certificate. 

![Capture d’écran 2021-07-31 à 00 40 17](https://user-images.githubusercontent.com/1178/127718334-d7062624-97c5-44b3-8887-df5aec9a0e43.png)

Also, just visually check-in stuff isn't secure AT ALL and I don't want to encourage wrong behavior since it will put the health of everyone at risk. It encourages forgery and could lead to a loss of trust in digital pragmatic solutions.

**Comment by n00d1e5** [comment]
Got that. Thanks for your reply.
Maybe, you can switch the position of certificate type and unique certificate identifier.
I think it better for the visual feeling.

And you can close the comment. :)

**Comment by clawfire** [comment]
I 100% agree the ICI is like ... who needs this? who gonna visually control this anyway 😂 

I would like to let others participate to this discussion too. Like @biou, @grischard 😃

**Comment by biou** [comment]
I find this use case interesting. I did not thought that the pass would be only visually checked.
On one hand, it is important to give the information needed to pass some check point. 
On the other hand, I have no idea if this is technically feasible @clawfire. Do we have the possibility to show this information on the front of the pass? 
Some people were complaining that we are already showing too much data, are this information not already too much for these people?

I would propose to try to consider this use case, with a "privacy preserving" option for those who want to show only the strict minimum.

**Comment by n00d1e5** [comment]
Currently, if I correctly remembered, the French AntiCovid only shows QR Code, name, birthday, and name of the vaccination (it shows Prifzer for BioNTech).
I do not know if this is too much for people who has privacy concern?

From a random Wallet generator, the information shown on the front can be defined by the design. Also the word under the QR-Code (no necessary to put the hits).

**Comment by clawfire** [comment]
> I would propose to try to consider this use case, with a "privacy preserving" option for those who want to show only the strict minimum.

I think CH and IT are working on sub implementations of a "privacy-preserving" code. But it's only a national implementation (not following EUDCC schema). 

What we can do is to generate a pass with fewer data in the field is the user select a "reduce the amount of information visible) for sure but I'm fearing it will backfire at them if they do 😂  (even if what matter should be what's inside the code)

**Comment by clawfire** [comment]
> Currently, if I correctly remembered, the French AntiCovid only shows QR Code, name, birthday, and name of the vaccination (it shows Prifzer for BioNTech).

Birthdate will be an issue probably. The name I think it's fine. 
Also, in France they only see that as EU DCC = vaccine which is so far from the truth 😁

**Comment by n00d1e5** [comment]
Here's the Australian official Wallet, it shows date of birth, document number (= unique certificate identifier), valid from (= date of vaccination). 
https://www.macrumors.com/2021/08/02/australian-covid-vaccine-cert-apple-wallet/

**Comment by clawfire** [comment]
@n00d1e5 thanks for pointing it out. definitly need to work on this

**Comment by n00d1e5** [comment]
I'm curious about what the official Spanish digital certificate looks like
https://9to5mac.com/2021/08/12/spain-adds-support-for-storing-covid-passports-in-the-apple-wallet/

**Comment by clawfire** [comment]
I need to find a spanish friend with a full vaccination scheme :p
