### ISSUE TITLE
[feature request]Load picture

### ISSUE THREAD

**Issue by clawfire** [clawfire/covid19-passbook-generator#11]
**Is your feature request related to a problem? Please describe.**
In France and Belgium, you only have your certificate in digital format. So you save a screenshot of it in your camera roll. Which you could want to import in the app directly.

**Describe the solution you'd like**
When scanning is in progress, tap an "import" button and select the picture from the camera roll

**Comment by biou** [comment]
Which formats do we need to support? JPG, PNG I suppose. Are some certificates also delivered as PDFs?

**Comment by clawfire** [comment]
Well I wouldn't go for PDF 'cause then your need to rasterize them (is that the good word?) ... I would go for PNG/JPG only IE what you could load from camera roll (not the file explorer).

**Comment by biou** [comment]
We have the [scanImage](https://github.com/nimiq/qr-scanner#single-image-scanning) method, which could help.
But I am wondering if it would work if we don't specify the coordinates of the QR-code. Maybe we need to add a way to crop the image before sending the image to the scanner.

**Comment by grischard** [comment]
The certificates are downloaded in pdf, so it's the logical desire path.

[PDF.js](https://github.com/mozilla/pdf.js) can apparently transform a pdf to an image.

**Comment by biou** [comment]
maybe we can even extract the QR-code from the PDF

**Comment by grischard** [comment]
Fixed in #28, without PDF support.

**Comment by clawfire** [comment]
I think good is good enough here 😃
