### ISSUE TITLE
[BUG]  won't focus on the qr code

### ISSUE THREAD

**Issue by Shaunah44** [clawfire/covid19-passbook-generator#112]
### Contact Details

Shaunah44@hotmail.com 

### What happened?

A bug happened! The scanner won't focus on the qr code

### What browsers are you seeing the problem on?

Chrome

### Are you browsing using

an Android Phone

**Comment by clawfire** [comment]
Hi there 😃 
Sadly, we cannot control the focus of the video feed. But here are some tips: 

1. Have a very bright light. It helps your camera making the focus between white and black ink on the paper
2. If you're trying to scan from a screen, try to take a step back. When you're too close to a screen, the screen backlight is captured by your camera and interfere with the recognition
3. if all of this doesn't work, take a picture of your qrcode with a good focus and use the import picture function.
