### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ConorORa** [clawfire/covid19-passbook-generator#113]
### Contact Details

conorora@gmail.com

### What happened?

My mums Covid cert won’t scan and when I try to upload a photo I can select the photo but nothing happens after that.

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hey there 😃 
Thanks for your bug submition. Can I ask which version of iOS or which iPhone you are using? 
We are now aware that the cryptographic functions needed to decode the qr code are not available below iOS14, which means iPhone 6 can't be used at all :(
