### ISSUE TITLE
[BUG] Start scanning and Import picture buttons not working

### ISSUE THREAD

**Issue by maybekitchen** [clawfire/covid19-passbook-generator#114]
### Contact Details

ross.reid.mcguire@gmail.com

### What happened?

The _Start scanning_ and _Import picture_ buttons on the site are not working for me.

I tried refreshing the page, re-entering the URL, refreshing the app—on Safari and Chrome, on both iphone and ipad.

### What browsers are you seeing the problem on?

Chrome, Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hi there 😃 
We are aware that to be able to manipulate the cryptographic functions to decode the QRcode, you need ios14 minium, which is unavailable on iPhone 6 sadly. 

What's you IOS version ?
