### ISSUE TITLE
[BUG] Cannot download into wallet

### ISSUE THREAD

**Issue by Amyyclarke21** [clawfire/covid19-passbook-generator#117]
### Contact Details

amyy.clarke21@gmail.com

### What happened?

A bug happened! I am trying to upload my covid vaccine  cert , it is uploaded but will not add to my wallet can u assist me 

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hi there 😃 

Can I ask which browser are you using?
Sadly, pushing a passbook in the Apple wallet require using the site in a plain browser and not an "in-app" browser like the one used in Messenger, Facebook, Twitter, ... That's a limitation both from the app creator (for Facebook, Messenger) and Apple (for Twitter, Instagram, ...).
