### ISSUE TITLE
[BUG] Name not retrieved correctly

### ISSUE THREAD

**Issue by aberisso** [clawfire/covid19-passbook-generator#118]
### What happened?

 After scanning the QR from my certificate, the name field from the generated passbook is wrong.

How it shows up in the certificate:
`SURNAME , NAME`

How it shows up in the passbook:
`SURNAME NULL NAME`

Seems to be caused by having spaces both before and after the comma.

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Would you mind sending me a copy of your certificate for inspection at hello@thibaultmilan.com ?
