### ISSUE TITLE
[BUG] Wrong name in the certificate + can't download

### ISSUE THREAD

**Issue by 00229531** [clawfire/covid19-passbook-generator#119]
### Contact Details

sfsamaral@gmail.com

### What happened?

I can’t download QR code to my wallet on mobile.And my name is wrong,missing a letter in my first name. It must be Sergio,not segio

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hey there, would you mind sending me your certificate at hello@thibaultmilan.com ? 

Unfortunately, I'm pretty sure about the fact that if there's an issue with your name, it's in your certificatE. I'm just decoding and using the information as it. You wouldn't be the first, sadly :(
