### ISSUE TITLE
[BUG] First names not properly displayed

### ISSUE THREAD

**Issue by AlainVagner** [clawfire/covid19-passbook-generator#120]
### What happened?

In the version 1.7, when you have 3 first names, you will get a < between the 2nd and the 3rd.
This is the case in the preview and in the passbook.

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Damn I never tested with 3 first names 🤔

**Comment by grischard** [comment]
I haven't experienced this with my three first names.

**Comment by clawfire** [comment]
> I haven't experienced this with my three first names.

You probably generated it before the version where I stop using the "local" name but do camel case + << escaping from the Latin name (because need to support non-latin travelers who are required to display their name in Latin alphabet)
