### ISSUE TITLE
[BUG] Cannot import picture form chrome on computer

### ISSUE THREAD

**Issue by pedrom41** [clawfire/covid19-passbook-generator#122]
### Contact Details

pedrodocu1979@gmail.com

### What happened?

A bug happened!

### What browsers are you seeing the problem on?

Chrome

### Are you browsing using

a computer

### Anything else?

It doesn't work. "No QR code found in image" and it is not true. Format: TIF.

**Comment by clawfire** [comment]
hello there.
So you try importing your picture correct? Is the resolution of the picture enough to not have the qrcode blured? 

would you mind sending me the picture to hello@thibaultmilan.com so I can see what's wrong ?
