### ISSUE TITLE
[BUG] Cannot scan nor import on iPhone

### ISSUE THREAD

**Issue by LCD1977** [clawfire/covid19-passbook-generator#123]
### What happened?

I am unable to scan my 2nd QR Code

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

### Anything else?

QR code of Page 2 of my Covid vaccination certificate doesn’t register regardless of whether i try to scan or whether i import a photo of it.

**Comment by clawfire** [comment]
Hello there.
Which country issued the certificate? 
When you import a photo of it, did you had a clear view of the QR code?
