### ISSUE TITLE
[BUG] Time stored in local time zone causes wrong birthday when traveling

### ISSUE THREAD

**Issue by grischard** [clawfire/covid19-passbook-generator#125]
### What happened?

The birthday is stored as a timestamp at midnight. If you were born on 1 January 1970 and are traveling in a time zone that is behind, your birthday will be shown as 31 December 1969.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Samsung Browser

### Are you browsing using

an iPhone

### Anything else?

Dates should be converted to strings

**Comment by clawfire** [comment]
Isn't it a bug from your wallet app itself? 

The certificate just contains dates, not datetime. 
Passbook requires DateTime but since I don't have it, I can only happen `T00:00Z` to the date 🤷🏼

**Comment by clawfire** [comment]
Ok, I have an idea. If I set the default date to T12:00Z it should work across all timezones?

**Comment by clawfire** [comment]
From [Apple doc](https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/FieldDictionary.html) you can use a `ignoresTimeZone` `true` when you're setting `dateStyle`

**Comment by clawfire** [comment]
hey @grischard we'll be able to try this soon 😃

**Comment by clawfire** [comment]
poke @grischard 😃  you should be able to test it.
