### ISSUE TITLE
[BUG] Uploading a TIFF file don't work

### ISSUE THREAD

**Issue by clawfire** [clawfire/covid19-passbook-generator#127]
### What happened?

When you're uploading a TIFF file, the picture cannot be read.
That's because the TIFF format isn't supported by the QR reader but we are still allowing it. Need to restrict it to PNG/JPEG/JPG I think.

### What browsers are you seeing the problem on?

Chrome

### Are you browsing using

a computer

**Comment by clawfire** [comment]
Should prevent TIFF upload since we are only supporting PNG + JPG

**Comment by sebam2k4** [comment]
Would like to have a go at this one. I have some changes already done locally, just can't push the branch. Probably missing permissions?

**Comment by sebam2k4** [comment]
This issue is related to browsers. Most , including Chrome and Firefox, do not have support for TIFF images for file uploads.  https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support

**Comment by clawfire** [comment]
Greeting @sebam2k4 .
So, you cannot indeed push directly to my repository. You need to fork my repository, do you change and submit a pull request with your change. Please read the CONTRIBUTING.md file for more information regarding how to contribute, including the fact we are working on the `develop` branch, while `main` is used for auto-publishing the web app.

**Comment by clawfire** [comment]
Should be fixed 😃
