### ISSUE TITLE
[BUG] on small screens, the scan button is hidden

### ISSUE THREAD

**Issue by biou** [clawfire/covid19-passbook-generator#13]
**Describe the bug**
on small screens, the scan button is hidden. It is the main CTA. It could be interesting to have it more visible, or maybe sticky.

**To Reproduce**
see screenshots.

**Expected behavior**
find a way to make this button more visible.

**Screenshots**
![IMG_7E2CD4CA1266-1](https://user-images.githubusercontent.com/1340376/123425882-f3778480-d5c2-11eb-9116-ded3410a9400.jpeg)

**Desktop (please complete the following information):**
 -Safari iOS 14.6

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.6
 - Browser Safari

**Comment by clawfire** [comment]
Definitely need to redesign the screens to get rid of that.
