### ISSUE TITLE
[BUG] My QR code is not being scanned.

### ISSUE THREAD

**Issue by Katjusha17** [clawfire/covid19-passbook-generator#132]
### Contact Details

katyamb99@gmail.com

### What happened?

My QR code is not being scanned.

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hey there 😃 
What's the version of ios you are using? 
Also, are you sure you're using safari and not a preview from Facebook/messenger / Instagram / Twitter / whatever?
