### ISSUE TITLE
[feature request] UX improvements

### ISSUE THREAD

**Issue by biou** [clawfire/covid19-passbook-generator#15]
- [x] explain that we manage 3 types of certificates

from @hellgy: 
- [x] the introductory text is too long: small text to reassure people and then a link "learn more" towards a page with  more details.
- [x] the text size is too small
- [x]  no back button available once we have scanned the code
- [x]  when scanning, it would be useful to have some "marks" on the video, to know where to place the QR code.

From @grischard:
- [x] explain that this is for iOS
- [ ] give an example
- [x]  video to show how to get the certificate from guichet.lu or links to the procedures of various countries
- [x]  adjust colors in the passbook background vs eu flag

**Comment by clawfire** [comment]
I'm not quite sure we need to explain how to get a certificate to everyone, it would be very time-consuming to do so. Plus we don't have an account in a foreign system to make a video about it. And people get their certificate either by mail, guichet.lu, pharmacy system, lab system ... never twice the same

**Comment by grischard** [comment]
Colours fixed in #26

**Comment by clawfire** [comment]
Plan to make an explainer video for the last remaining point.
