### ISSUE TITLE
[BUG] iPhone 12 pro max camera can't focus

### ISSUE THREAD

**Issue by clawfire** [clawfire/covid19-passbook-generator#21]
**Describe the bug**
The default selected camera on the iPhone 12 pro max can't focus on short-range. It doesn't happen with a 12 or 12 pro

**Expected behavior**
Being able to focus 😁  Expect that we can consider several solutions. Users tend to be used to tap to focus but it not gonna work with the actual implementation. Being able to select a different camera could be an option.

**Comment by biou** [comment]
linked to #23, we can solve the 2 bugs by implementing the selection of the camera.

**Comment by biou** [comment]
We should also display an error message when there is no camera at all.

**Comment by biou** [comment]
It seems that there is no way to force the focus via JavaScript.

**Comment by clawfire** [comment]
Oh I missed that one. That's not a force focus, it's the telelens that is selected by default on 12 pro (don't know why). We should add a camera switch button
