### ISSUE TITLE
[BUG] I don't have a qr code

### ISSUE THREAD

**Issue by Rorysmyth64** [clawfire/covid19-passbook-generator#235]
### Contact Details

rorycatherinesmyth@gmail.com

### What happened?

A bug happened! Covid recovery is from United States so there is no QR code to upload. 

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

### Anything else?

How can I upload foreign COVID recovery documentation?

**Comment by clawfire** [comment]
Hey there.
So far, this application only supports European Digital Covid Certificate. It then requires a QR code to be scan/upload.

We plan to expand to other countries/types of QR code but it will not be an app to create passes from scratch since they will have no legitimity. 

Regards
