### ISSUE TITLE
[feature request] Display a message if iOS user comes with other browser than safari 

### ISSUE THREAD

**Issue by clawfire** [clawfire/covid19-passbook-generator#25]
**Is your feature request related to a problem? Please describe.**
Only safari on iOS allow to open a passbook. Chrome or Firefox fail to even download the file (i suspect iOS catch it and hide it)

**Describe the solution you'd like**
A message when we detect iOS user coming from anything than safari to warn them about the fact the save to wallet will not work could do the trick 

**Describe alternatives you've considered**
Feature detection would be better but I don't know any test for add to wallet capability.

**Comment by biou** [comment]
Is this problem only appearing on iOS? What about Android webviews?

**Comment by peroxy** [comment]
I think it's actually possible to make it work with Firefox/Chrome, I have tried using app.getcovidpass.eu website and they managed to do it, not sure how..

**Comment by clawfire** [comment]
I saw few other solutions which are generating the pass on their serveur and they return a file to download where we are generating everything on the browser itself to prevent any personal data transmission.

Info take a closer look on what we could do to get a better browser coverage

*Milan Thibault*
📝 clawfire.net ( http://clawfire.net/ ) • 🐦 @clawfire ( https://twitter.com/clawfire ) • 🗣 he/him

🎥 Find me every Thursday at 7pm talking about #nocode in French, on Twitch ( http://twitch.com/thibault_nocode )

**Comment by clawfire** [comment]
> Is this problem only appearing on iOS? What about Android webviews?

✅  working on a regular review (such as Slack)
❌  not working on Facebook Messenger's web view (no access to camera feed)
❌  not working on Facebook's web view (access to camera, scanning slow AF, can't download)
❌  not working on Instagrams's web view (access to camera, scanning slow AF, can't download)

I would like to try a feature detection approach but ... not sure how to test you can download things without ... well ... downloading something (especially it fail silently like the webview is preventing the download without raising error)
