### ISSUE TITLE
[BUG] Date of Birth disappeared in 2.1.1

### ISSUE THREAD

**Issue by n00d1e5** [clawfire/covid19-passbook-generator#281]
### What happened?

You can try with you current certificate in Luxembourg

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

### Anything else?

Once the QR-code is scanned on the website, there does is the date of birth alone with name (and name) and unique certificate number. But when I click save in your wallet, the date of birth disappears.
If I correctly remembered, there was no such issue for me with version 2.0.1, it seems to be an issue from https://github.com/clawfire/covid19-passbook-generator/commit/92e4069a93e3b1a8bea9fc44476048405bc43160, not sure...

**Comment by janbrasna** [comment]
yup +1, confirming on freshly generated (cz) pass: the date is not shown. it is however saved in the .pkpass in both instances (e.g. 1977-05-25T00:00) so there must be some iso8601 formatting precision  dislikes, or some of the date presentation flags don't like the input?

**Comment by biou** [comment]
I confirm that the issue is also there on a LU pass, date of birth and date of vaccination are missing.

**Comment by clawfire** [comment]
>.< 
Fixing one issue, creating one. Homeostasis ... 

@grischard definitely this commit, need to investigate.
@janbrasna Good idea. I'll gonna check this.

**Comment by clawfire** [comment]
Should be fixed now 😃

**Comment by liamcunn** [comment]
Yes, can confirm that it is now fixed. Just successfully imported vaccination cert into Apple Wallet. The information that was previously missing is now imported successfully.
