### ISSUE TITLE
[BUG] Safari 14 requirement on desktop not detected

### ISSUE THREAD

**Issue by janbrasna** [clawfire/covid19-passbook-generator#282]
### What happened?

After successfully recognizing a QR on camera, the app stops on unhandled promise rejection. ReferenceError in `@cbor/lib/constants.js` as in the screen shot attached.

### What browsers are you seeing the problem on?

Safari (desktop 13.1.3)

### Are you browsing using

a computer (macOS Catalina 10.15.7)

### Anything else?

![Screen Shot 2021-10-10 at 23 01 35](https://user-images.githubusercontent.com/1784648/136713000-90fac011-35f1-470b-b9d6-5a07077943b2.png)

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.3 Safari/605.1.15` https://www.whatismybrowser.com/w/9F68GL4

**Comment by janbrasna** [comment]
Ah, okay, the app only works in Safari 14+ … however I didn't run into any error message stating so, as is described in https://github.com/clawfire/covid19-passbook-generator/issues/54#issuecomment-894512939 🤷‍♂️

**Comment by clawfire** [comment]
That's weird, you should have seen a message. However, there's no feature detection mechanism for bigInt I know, so I need to rely on parsing the userAgent, which is not always reliable to guess which version you are using :/

**Comment by clawfire** [comment]
A fix is on its way 😃

**Comment by janbrasna** [comment]
Ah, gotcha! I see it now. However, that doesn't work as 

`$.ua.browser.version < 14` compares a string e.g. "13.1.3" so that's false anyway:

![Screen Shot 2021-11-02 at 18 37 29](https://user-images.githubusercontent.com/1784648/139917166-3e5104de-eafc-422f-b8a7-9125a28319b5.png)

Maybe a parseFloat() would be the right choice? As:

![Screen Shot 2021-11-02 at 18 37 55](https://user-images.githubusercontent.com/1784648/139917304-9890303d-dd35-422a-a4de-6417ea72daae.png)

I'd propose a PR however you'd prolly want to test it more than my code smell knowledge goes…;]

**Comment by clawfire** [comment]
hum. Can't really use `parseFloat`here because `13.1.3` will be converted into `13.1` I guess (hope). 
I'll have to check, the ua-parser should have a method for that.

**Comment by janbrasna** [comment]
@clawfire Yup, it parses 3.14whatever to 3.14 just fine… which is good enough for this major version comparison needed I guess. But I'd rather let that to whatever is your liking, algorithm-wise;)

**Comment by clawfire** [comment]
I may try https://www.npmjs.com/package/compare-versions
