### ISSUE TITLE
"Safari cannot download file" error message

### ISSUE THREAD

**Issue by brianbovi** [clawfire/covid19-passbook-generator#285]
Upon clicking "Save to my wallet" i get the error "Safari cannot download file".

I also tried to Airdrop the .pkpass file downloaded on my mac to the phone, which results in a similar message "Failed to save item. Save to iCloud Drive instead?".

**Comment by clawfire** [comment]
That's weird.
Can we get a bit more context? Are you using an iPad, iMac, iPhone?
Which version of which OS?

Thanks

**Comment by alexkey89** [comment]
same issue on iOS 14.7.1. Pass is generated but when clicking on add pass to wallet safari says: "Safari cannot download file"

**Comment by clawfire** [comment]
Thanks for letting me know. I'll gonna test with this environment.

**Comment by alexkey89** [comment]
> Thanks for letting me know. I'll gonna test with this environment.

sure, after further testing, seems that the issue appears only on recovery certificates
