### ISSUE TITLE
I can’t scan my covid cert 

### ISSUE THREAD

**Issue by Dearbhile** [clawfire/covid19-passbook-generator#288]
### Contact Details

dearbhilemc02@gmail.com

### What happened?

It won’t let me scan my covid cert from another phone and it can’t find the QR code when I upload of screenshot of it 

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

### Anything else?

![Uploading E67C8CE7-B4ED-4C27-98C8-2470AB524F59.png…]()

**Comment by clawfire** [comment]
Hello there 😃 

Which iPhone model and which iOs version are you using?
