### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Justinmoran18** [clawfire/covid19-passbook-generator#289]
### Contact Details

justinmoran2617@gmail.com

### What happened?

Won’t let me save to wallet 

### What browsers are you seeing the problem on?

Chrome

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hi there.
You should have got a message warning you that you NEED to use Safari to save a pass in your wallet. That's Apple requirement and there's no possibility to go around it.

Regards.
