### ISSUE TITLE
[feature request] new design

### ISSUE THREAD

**Issue by biou** [clawfire/covid19-passbook-generator#29]
![Plan de travail 5-100](https://user-images.githubusercontent.com/1340376/124147773-4bb0f980-da8f-11eb-8fd7-a4b8370233e2.jpg)
![Plan de travail 4-100](https://user-images.githubusercontent.com/1340376/124147784-4d7abd00-da8f-11eb-824f-bd55fc70b610.jpg)
![Plan de travail 3-100](https://user-images.githubusercontent.com/1340376/124147786-4e135380-da8f-11eb-9a38-c92994d1cdfe.jpg)
![Plan de travail 2-100](https://user-images.githubusercontent.com/1340376/124147794-4f448080-da8f-11eb-9e6a-7cac573d63d9.jpg)
![Plan de travail 1-100](https://user-images.githubusercontent.com/1340376/124147799-4fdd1700-da8f-11eb-8d60-a34285517b60.jpg)

**Comment by grischard** [comment]
What about using the logo from https://github.com/eu-digital-green-certificates instead of the EU flag while we're at it? In the app's colours?

**Comment by clawfire** [comment]
> What about using the logo from https://github.com/eu-digital-green-certificates instead of the EU flag while we're at it? In the app's colours?
> 
> ![81561767](https://user-images.githubusercontent.com/1556567/124183333-59c74000-dab8-11eb-9fce-3c63a62afbca.png)

Is it something official? Can we find some other usage of this logo in the wild? I didn't saw it on the PR guidelines :(
