### ISSUE TITLE
[BUG] Date of birth missing from wallet cert

### ISSUE THREAD

**Issue by Eoghan1232** [clawfire/covid19-passbook-generator#291]
### Contact Details

eoghanrussell123@gmail.com

### What happened?

When cert is imported into apple wallet, the date of birth field is blank, but its show in the preview before downloading.

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Yep. I gonna close this one and continue to #281 if that's good for you 😃
