### ISSUE TITLE
[feature request] EDGE-Mobilebrowser Support

### ISSUE THREAD

**Issue by pascom1969** [clawfire/covid19-passbook-generator#292]
### Contact Details

pcomini@hotmail.com

### Is your feature request related to a problem? Please describe.

I was unable to add my (Swiss) certificate via EDGE mobile browser and I didn't get any error-message.

### Describe the solution you'd like

Please make sure, that the certificate can also be imported via EDGE-browser (which is my personal default browser). ISince the import didn't work (without any message), I copy/pasted the URL into Safari and then the wallet-import worked.

### Describe alternatives you've considered

At least a message telling that EDGE-browser (what about Chrome?) isn't supported and only (?) Safari instead would be helpful.

### Anything else?

It's a great service! Very well done! :-)
Pascal Comini, Switzerland

**Comment by clawfire** [comment]
Hi there 😃 

Sadly, pushing a passbook in the Apple wallet requires using Safari only so far. That's Apple's decision and there's nothing we can do about it.

**Comment by pascom1969** [comment]
Dear Thibault
Thanks for your clarifications and feedback.
Apple's decision (once again) doesn't suprise me.
And here's the screenshot.
![20211101_105301000_iOS](https://user-images.githubusercontent.com/37907346/139661258-389729a5-a8bb-445a-8837-93667c1b58f6.jpg)
JFYI: Wehenver I'm using my Apple watch in order to show my certificate, the security-guys get thrilled :-) They simply "love" this (as I do).

**Comment by clawfire** [comment]
I should check the code. I guess you didn't get warned because it's an Edge browser but ... it should 😄

**Comment by pascom1969** [comment]
You're right :-) I'm really not aware that I received any warning.
Probably I'm the only using EDGE on iOS :). So if Chrome provides a warning (haven't tested it), I guess most users will be safe.

**Comment by clawfire** [comment]
Weirdly, I just downloaded Edge on iOS and went to the project page and got hit by the message instantly.
![IMG_1087](https://user-images.githubusercontent.com/1178/139666603-a9117546-d3f1-46e3-94a7-60ac336c0486.PNG)

**Comment by clawfire** [comment]
Thanks for raising the concern anyway. I tested it on a few versions of Edge (plying with the UA) and it looks like I got caught every time.

**Comment by pascom1969** [comment]
TBH: I have somewhen seen this message. But I couldn't say when and if related to the certificate.
So in this case please feel free to close this request.
And thanks a lot for your your support and your great work :-)
