### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by liamcunn** [clawfire/covid19-passbook-generator#297]
### Contact Details

Liam.cunnane@yahoo.co.uk

### What happened?

Hi,

I've just tried to save a Covid-19 Vaccination certificate to my Apple Wallet. 

Running ios 15.1. 

The pass generated is missing the date of the birth and the date of the most recent vaccination. 

I have an earlier certificate imported to Apple wallet on my phone that displays all the required information. 

Liam 

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hey there. 
#287 is already open regarding this issue and a fix is on its way 😃
