### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by robyneverard** [clawfire/covid19-passbook-generator#298]
### Contact Details

robyneverard1@gmail.com

### What happened?

A bug happened! I try to download my file and it says safari cannot download this file.

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hey there 😃 
Which version of IOS are you using and on which iPhone model please ?

**Comment by robyneverard** [comment]
i’m using IOS 14.7.1 on an iphone 11

**Comment by valentinoangioletti** [comment]
Was this a Covid Recovery Cert?
