### ISSUE TITLE
[feature request] Add BE & GR instructions

### ISSUE THREAD

**Issue by clawfire** [clawfire/covid19-passbook-generator#300]
### Is your feature request related to a problem? Please describe.

covidpass.doctoranytime.be & covidpass.doctoranytime.gr contains instructions for BE and GR pass that are not in the community app.

### Describe the solution you'd like

backport instructions

**Comment by clawfire** [comment]
If anyone wants to handle it, please edit only the `index.html`. All the other files are handled by the translation engine.

**Comment by janbrasna** [comment]
So the 1:1 port is in #301 however, it's in identical as-is state as the commercial sites, incl. issues:
1. BE sentence is missing the french link (couldn't find one),
2. GR diverged in #266 so the PR changes that to the commercial one.

Not sure about picking either version or fixing missing site. Just transferred from DA version.

**Comment by clawfire** [comment]
Hum ... the PR is merged on `develop` and should be display on the next release

**Comment by janbrasna** [comment]
👍 The Greek has been fixed as per review, however the Belgian text misses one link/locale if I understand that correctly. Tried to blindly guess the URL for missing version but with no luck. Maybe someone knows better?
