### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by FOT2021** [clawfire/covid19-passbook-generator#307]
### Contact Details

fionaotoole3@hotmail.com

### What happened?

I tried to upload my covid 19 recovery certificate (Ireland) to Apple Wallet, a pop up comes up saying “Safari cannot download  this file”

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by FOT2021** [comment]
Thanks for nothing 🙄

Fiona O'Toole
________________________________

**Comment by FOT2021** [comment]
Again thanks for nothing 🙄

Fiona O'Toole
________________________________

**Comment by clawfire** [comment]
Hey @FOT2021 ,

Thanks for replying to the 🤖  bot ... I guess. 🤷🏼‍♂️ 

By the way, this kind of attitude don't make open-source contributor, who work for FREE to offer you such tool, wants to help 🙄  but anyway 

There's a known issue ongoing with recovery certificate, which should be fixed and put online end of the weekend. 
MADE.
ON MY SPARE TIME. 

You can check if the version on https://covid19passbook.netlify.app/ changed to something bigger than 2.2.0, it should be fix and you can try again.

**Comment by FOT2021** [comment]
Super thank you so much - much appreciated

Fiona O'Toole
________________________________
