### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Seanyeeea** [clawfire/covid19-passbook-generator#310]
### Contact Details

darcysean@hotmail.com

### What happened?

Covid cert not adding to phone wallet once imported.

A bug happened!

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hey @Seanyeeea 

Thanks for the bug report. Which kind of certificate are you trying to import ? Recovery, Vaccine or test ?
