### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Dlohan94** [clawfire/covid19-passbook-generator#315]
### Contact Details

daireplohan@gmail.com

### What happened?

A bug happened! This won’t allow me add my covid cert to my Apple wallet. See below:
![08E24F2B-5981-4C70-9621-B86F86F9F8C3](https://user-images.githubusercontent.com/95778979/145283345-8755a844-f000-432f-b158-c05129eb35ac.png)

### What browsers are you seeing the problem on?

Chrome, Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hey @Dlohan94 

Thanks for your report. 

The issue with recovery certificate has been found and fix is under the way. It should be online by end of the weekend. 

You can check on the website https://covid19passbook.netlify.app/ if the version number on the lower left part of the window is more than 2.2.0 (the current version) then you can give a try 😃
