### ISSUE TITLE
Vaccination Certificate can not be saved in Iphone wallet

### ISSUE THREAD

**Issue by AGSCHOL** [clawfire/covid19-passbook-generator#316]
### Contact Details

schol@pt.lu

### What happened?

I scanned my Lux vaccination certificate via your website , it was ready . The only thing I needed to do is push button ‘save in wallet’ … however that does not work.
In June 21 it worked fine.. please assist,
Thanks

### What browsers are you seeing the problem on?

Chrome

### Are you browsing using

an iPhone

**Comment by RemingtonDev** [comment]
It only works on Safari it seems.

**Comment by clawfire** [comment]
Hey @AGSCHOL,
Thanks for letting me know of your issue. @RemingtonDev is right. On iPhone, Chrome has no access to your wallet. That's an Apple limitation and there's NOTHING we can do about it. You **must** use Safari to generate your certificate if you want to add it into your iPhone wallet. 

Also, you should had seen a screen when you visit the website with chrome explaining this 😁 

Cheers.
