### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by IRG1959** [clawfire/covid19-passbook-generator#32]
hi there,
I scanned my Covid QR and when I press on save to wallet, I see an activity as a scrolling bar goes left to right on top as if something is happening but nothing shows in my iPhone wallet. Can you help me?  Thank you in advance

**Comment by grischard** [comment]
Hi @IRG1959 

Thank you for opening your first issue. Can you tell us what iPhone model, what browser and what iOS version you're using? What country is your QR code from?

**Comment by IRG1959** [comment]
iPhone X
14.6
Mostly Chrome
Luxembourg
😀

**Comment by grischard** [comment]
Moien :).

It's probably because Apple doesn't allow Chrome to add stuff to the Wallet app. Can you try reproducing the bug in Safari?

Related bug: #25

**Comment by IRG1959** [comment]
Let me try

**Comment by IRG1959** [comment]
Edge did not work
But Safari did so you were right...Apple hates all non Apple 😵‍💫
Thank you for help

**Comment by clawfire** [comment]
Hey @IRG1959 thanks for your bug report.
As @grischard said, sadly Apple doesn't allow even downloading the passbook file from another browser. 

We planned to put a little banner (see #25) to explain that when we detect another browser. I'll close your ticket so far. That's a million time to give it a try ❤
