### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by rckingoriain** [clawfire/covid19-passbook-generator#333]
### Contact Details

rckingoriain@gmail.com

### What happened?

A bug happened!I can scan my cert but it won't save to my wallet

### What browsers are you seeing the problem on?

Chrome

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hello there 😃 
Thanks for letting me know. Any chance it's a recovery certificate ? We have an ongoing issue with them and it should be fixed by end of the weekend 👍🏼 

If not, please let me know

**Comment by clawfire** [comment]
Oh. I just see that you mention you're using Chrome.

You cannot use Chrome to insert certificate in your wallet. That's Apple restriction and there's nothing I can do about. You should have seen a warning screen at launch saying you **must use Safari instead**
