### ISSUE TITLE
Safari cannot open this file

### ISSUE THREAD

**Issue by FranMcA** [clawfire/covid19-passbook-generator#338]
I can get covid cert generated but can’t put it into Apple wallet. I have turned phone off and on. Have tried with different phone but it won’t work

**Comment by clawfire** [comment]
Hello there,
Thanks for contacting me 😃  Well, I bet it's from a recovery certificate. We have an issue with this at the moment but should be fixed in the next version, online by end of this weekend 👍🏼

**Comment by FranMcA** [comment]
Hi and thanks for the reply. Yes it’s a recovery cert! So I’m not alone. 
How will I know issue is fixed? Just by trying again?

**Comment by clawfire** [comment]
You can check on the website https://covid19passbook.netlify.app/ if the version number on the lower left part of the window is more than 2.2.0 (the current version) then you can give a try 😃

**Comment by FranMcA** [comment]
Just want to let you know this works now. Thanks so much 👍🏻
