### ISSUE TITLE
[feature request] i18n

### ISSUE THREAD

**Issue by biou** [clawfire/covid19-passbook-generator#34]
**Is your feature request related to a problem? Please describe.**
Some of our french speaking users have problems understanding english. They would be interested in a french translation.

**Describe the solution you'd like**
Add a language selector.

**Describe alternatives you've considered**
Google Translate? Really? 😄

**Comment by clawfire** [comment]
😕

Ok that's not complicated with mustache + there's already a i18n data API on all semantics elements.

**Comment by clawfire** [comment]
This gonna be some high priority soon since I found contributors for content in FR, NL, ES, GR

**Comment by clawfire** [comment]
Translations received 😃

**Comment by AlainVagner** [comment]
@clawfire I would also propose to [localize the passbook files](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW54) themselves.  What do you think?

**Comment by clawfire** [comment]
> @clawfire I would also propose to [localize the passbook files](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW54) themselves. What do you think?

love the idea. We need to think how to do that with crowdin properly 👍🏼

**Comment by clawfire** [comment]
TODO: 

- [x] Implement translation service
- [x] Generate translated files
- [ ] Language switcher
- [ ] Move the API call after the first scan button click to be sure to not call API before knowing which language (so no call for nothing)
