### ISSUE TITLE
[BUG] Safari cannot download this file on Recovery Certificate

### ISSUE THREAD

**Issue by mandypost97** [clawfire/covid19-passbook-generator#343]
### Contact Details

mandypost@gmail.com

### What happened?

I'm attempting to upload my Covid Recovery Certificate to my Apple wallet. I scanned my certificate using my phone and clicked on "Save in your wallet." Then I receive this message, "Safari cannot download this file." Can you help me please?
Thank you,
Mandy

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hey there. We had issue with recovery certificate but it should be solved by end of the weekend 😃
I deleted your picture to prevent anyone to decode your daughter data ;)
