### ISSUE TITLE
[BUG] Booster (3/3 shots) Generated QR codes don't pass 2G+ requirements

### ISSUE THREAD

**Issue by jamesg311** [clawfire/covid19-passbook-generator#354]
### What happened?

My wife and I have recently gotten booster shots in Luxembourg. When we upload our new QR code from the Luxembourg government, it generates a different QR code in the wallet app that does not pass the 2G+ CovidCheck.lu requirements. When we scan the printed out QR codes it passes the 2G+ correctly.

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Wow that's definitly a weird one.
I'll get in touch with you by email to see how I can debug that. Because I just reuse the code content as it without changing anything.

**Comment by jamesg311** [comment]
Hi I discovered this when trying to scan my passbook Qr Code from my Apple Watch. I have now discovered that the Apple Watch wallet app wasn't updating the pass itself and had an old QR code. I deleted them and the new ones I had created synced and worked fine. Can close this issue.
