### ISSUE TITLE
How to get booster qr registered ?

### ISSUE THREAD

**Issue by robertvandenoord** [clawfire/covid19-passbook-generator#355]
### Contact Details

robertvandenoord@hotmail.com

### What happened?

I do not seem to get my Covid booster qr registered. How can I do this?

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hey there,
When you get your covid booster, you receive a brand new certificate you need to scan here. It's a separate certificate, not an update on the original one.

**Comment by robertvandenoord** [comment]
Yes I have that, i tried with the tips of light etc, but does not get scanned. It does work, if you scan it under covid check app it says, it has the booster.

also i tried a photo, but did not work either

**Comment by clawfire** [comment]
Could you send me a picture of the certificate to hello@thibaultmilan.com so I can check why the code isn't read ? 

Also, which device are you using ? Phone or computer ? Which brand ? Which OS version ? Which browser ?

**Comment by clawfire** [comment]
After exchanges by email with @robertvandenoord , it seems it's a camera capture / focus issue. The PDF version acquired on guichet.lu works well, while the printed version didn't.
