### ISSUE TITLE
[BUG] manage network errors

### ISSUE THREAD

**Issue by biou** [clawfire/covid19-passbook-generator#36]
**Describe the bug**
when there is problem to reach the backend, scanning fails with a white screen, no error message and no possibility to try again.

**To Reproduce**
1. load the page.
2. go to airplane mode
3. scan the code
4. get a white page and that's it.

**Expected behavior**
display an error message and propose to try again.

**Screenshots**
similar to the screenshot in #35 

**Smartphone (please complete the following information):**
- iOS

**Comment by clawfire** [comment]
oh there's nice libraries that detect offline/online and "pause" your webapp. I need to find that again

**Comment by clawfire** [comment]
I did something to handle this on `develop`, will go on the next release 😃
