### ISSUE TITLE
[feature request] Update valueset

### ISSUE THREAD

**Issue by tw0517tw** [clawfire/covid19-passbook-generator#360]
### Is your feature request related to a problem? Please describe.

I was trying to generate a card but it says my QR code not containing information needed. My vaccine is new on the product list https://github.com/ehn-dcc-development/ehn-dcc-valuesets/blob/main/vaccine-medicinal-product.json#L152-L158 .

### Describe the solution you'd like

Update valueset to newer version. https://github.com/ehn-dcc-development/ehn-dcc-valuesets

**Comment by clawfire** [comment]
hey there 😃 

Weird because the valueset I use is a fallback if the EU service cannot be contacted to download the last one. I'll update to the latest anyway.

**Comment by tw0517tw** [comment]
Hi!

I'll also take a look at the certificate QR code generated by our government to see if there are bugs in there.

**Comment by clawfire** [comment]
Hey I saw the PR 👍🏼 
That's awesome 😃  I just put a comment to double check about something I may missed and I'll merge it ASAP.
