### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by janehn** [clawfire/covid19-passbook-generator#387]
### Contact Details

Jane.holst.kristensen@gmail.com

### What happened?

I can’t import my certificate - the camera doesn’t take a picture and when I take a picture normally of the QR code and try to import it it says that no QR code is in the picture…

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hi there 😃 

Can I ask if you see your camera in the camera selector or not ?

Sadly, accessing the camera require using the site in a plain browser and not an "in-app" browser like the one used in Messenger, Facebook, Twitter, ... That's a limitation both from the app creator (for Facebook, Messenger) and Apple (for Twitter, Instagram, ...).

**Comment by janehn** [comment]
Hello,

Yes I see the camera fine but nothing happens (have tried in Safari and
chrome and it's the same) - and when I take a picture and import it it
doesn't recognize any qr-code.

Best regards,
Jane


Den ons. 16. mar. 2022 kl. 16.08 skrev Thibault Milan <
***@***.***>:

**Comment by janehn** [comment]
15.3.1

Den ons. 16. mar. 2022 kl. 16.30 skrev Thibault Milan <
***@***.***>:

**Comment by clawfire** [comment]
That's weird 🤔 
Could you email me the picture so I can troubleshoot it on my side? hello@thibaultmilan.com

**Comment by janehn** [comment]
ons. 16. mar. 2022 kl. 16.44 skrev Thibault Milan ***@***.***
