### ISSUE TITLE
[BUG] it opens with my front camera as default

### ISSUE THREAD

**Issue by daTr0ll** [clawfire/covid19-passbook-generator#392]
### Contact Details

tomas@bremin.eu 

### What happened?

Please, set the rear camera as default for scanning a certificate. 

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hi there,
Under the camera live feed you can use a selector to change the camera. 
The thing is, I can either get the list of the camera and initialise on the first the phone gave me or ask it to display the rear camera but without any garantee it will do it. 

And iPhone pro have 2 rear camera. A macrophoto one and the "normal" one. If I ask the phone to "use the rear camera" it use ... the macro one -_-. Making users of iPhone pro unable to use it. I observed kinda similar behavior with some Samsung phones. 

Soooo, I decided to make it accessible to more people by putting a select and, by default, using the first of the list I get from the phone (there's no details in the list returned like rear or front to use 😢  )
