### ISSUE TITLE
[BUG] Can't import a screenshot

### ISSUE THREAD

**Issue by ElianeGF** [clawfire/covid19-passbook-generator#53]
**Describe the bug**
My boyfriend tried to add the certificate to his Iphone wallet but is doesn’t work. 
It mentions that the QR code is not valid.
Can you tell me what to do in this case?

[Screenshot REDACTED]

**Comment by grischard** [comment]
Hi Eliane and Kevin,

Are you OK with your birthdate and vaccine info being on a public bug tracker? We can delete it otherwise.

The QR code is maybe a bit blurry to decode - try zooming into the pdf, taking a screenshot, and then uploading that?

**Comment by ElianeGF** [comment]
Hi,

I didn’t think about it. Can you please delete it?
We will try this and if it doesn’t work, I will come back to you.

Kind regards,
Eliane GOMES

Envoyé de mon iPhone

Le 12 juil. 2021 à 11:46, Guillaume Rischard ***@***.***> a écrit :

﻿

Hi Eliane and Kevin,

Are you OK with your birthdate and vaccine info being on a public bug tracker? We can delete it otherwise.

The QR code is maybe a bit blurry to decode - try zooming into the pdf, taking a screenshot, and then uploading that?

**Comment by clawfire** [comment]
hello @ElianeGF , I removed your screenshot by editing your first comment 😃 
Talking about the issue you have, your boyfriend made a screenshot of the entire A4 PDF. But his phone resolution isn't good enough to let our app read the QRcode.

2 solutions: 
1. He can zoom on the qrcode (really the app just need this)
