### ISSUE TITLE
[BUG] QR code not recognized

### ISSUE THREAD

**Issue by tvanbeek** [clawfire/covid19-passbook-generator#56]
~~The camera is on but the app does not recognize the QR code. Also, import photo doesn't work on iOS.~~

~~Tried on iPhone 12 mini, iPhone 7, iMac 21.5 2019.~~

~~When I point the phone at the printed A4 in regular Camera app it does detect the QR code.~~

~~When I use the "Import picture" function on MacOS I get a message `No QR code found in image`.~~

When I scan the QR-code with the CovidCheck.lu app it immediately recognizes the QR code without issue.

The print I use is the "EU Digital Covid Certificate" I received at the vaccination center.

EDIT:
So I after trying a bunch more times now its does scan, but then nothing happens, I dont get a file to download or a popup asking me to add a card to my wallet.

**Comment by clawfire** [comment]
Hey @tvanbeek ,
Any chance you are using a different browser than safari? It's an Apple limitation that wallet cards can be only generated on safari 🤷🏼 . I know that sucks but I have 0 control over it so far 😞

**Comment by tvanbeek** [comment]
After trying many times at one point it just worked. Thanks, very cool project!

**Comment by clawfire** [comment]
Ok cool. Sorry it didn't work the first time 😃 
Don't hesitate to share.
