### ISSUE TITLE
[BUG] Not saving to wallet 

### ISSUE THREAD

**Issue by DonallQuinn** [clawfire/covid19-passbook-generator#57]
**Describe the bug**
Although the QR code scans and the correct information appears, when I tap Save to Wallet, nothing happens. No error message but nothing appears in the wallet.

**Smartphone (please complete the following information):**
 - Device: iPhone SE 
 -  Model :MP862B/A
 - OS: iOS 14.6
 - Browser Firefox
 - Version Firefox Daylight 34.2 (5301)

**Additional context**

**Comment by biou** [comment]
Hey, thanks for this issue. Could you please try again on Safari? At the time being, we cannot save to Wallet on Firefox and Chrome on iOS.

**Comment by DonallQuinn** [comment]
Will do, thanks.

Best Regards

Donall Quinn
+353-(0)87-2504847
________________________________

**Comment by clawfire** [comment]
@DonallQuinn is it working ? 😃

**Comment by DonallQuinn** [comment]
Hi

Yes, I tried it with Safari and it worked perfectly. Thanks very much.

Best Regards

Donall
P: +353-(0)87-2504847

***@***.***D77C8B.72783D60]
