### ISSUE TITLE
[BUG] Cannot scan nor import qrcode

### ISSUE THREAD

**Issue by debsrowan** [clawfire/covid19-passbook-generator#58]
**Describe the bug:**

When trying to import picture nothing happens QR code cannot be read and QR code also can’t be read with the scan QR code option.

**Expected behaviour:**

I expected to be able to upload Covid certificate to my Apple wallet.

**Comment by clawfire** [comment]
Hi there 😃 

Can I ask which browser are you using?

Sadly, accessing the camera require using the site in a plain browser and not an "in-app" browser like the one used in Messenger, Facebook, Twitter, ... That's a limitation both from the app creator (for Facebook, Messenger) and Apple (for Twitter, Instagram, ...).

Also, pushing a passbook in the Apple wallet requires using Safari only so far.

We are working on some improvements to detect and tell users what to do when they are in that case #25
