### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Maylou70** [clawfire/covid19-passbook-generator#59]
Nothing happens when I try and scan QR. I tried using my camera and got message in photo attached. Absolutely nothing happens when I try to use your link
![0E12314D-1BF6-46CA-BEBE-DDF8A6757FFB](https://user-images.githubusercontent.com/87447005/125684421-9ac747c6-2848-4e3c-bfb6-09e99db76ed2.jpeg)

**Comment by cfanoulis** [comment]
Hi! Did you try scanning in the webpage?

**Comment by clawfire** [comment]
Hi 😃 
The code cannot be scanned with your camera app. You need to go to https://covid19passbook.netlify.app/ and then click the blue "start scanning" button 😃

**Comment by Maylou70** [comment]
Hi. Yes, I tried scanning in the webpage and it didn't work anytime I tried
yesterday but this morning I tried again and it worked so I'm sorted thanks!

**Comment by Maylou70** [comment]
Hi, yes, I did that and 3 times it didn't work yesterday. This morning I
gave it another go and it worked, so I'm sorted thanks.

**Comment by cfanoulis** [comment]
Great! Please make sure to close this issue if your issue is resolved!
