### ISSUE TITLE
[feature request] Use transcribed name where present

### ISSUE THREAD

**Issue by cfanoulis** [clawfire/covid19-passbook-generator#60]
### Contact Details

thateudccapp@fanoulis.dev

### Is your feature request related to a problem? Please describe.

Currently, passes provide the name in it's native script, which may not always be the Latin alphabet (e.x. Greek names: ΧΑΡΑΛΑΜΠΟΣ ΦΑΝΟΥΛΗΣ instead of CHARALAMPOS FANOULIS), which can be a hinderance for travelling

### Describe the solution you'd like

According to the EUDCC specification, the QR code provides the namet and surnamet (to be doublechecked), which are transcribed to always be in Latin. The pass should always use those, instead of the name in Native Script

### Anything else?

https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_json_specification_en.pdf
https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v4_en.pdf

**Comment by clawfire** [comment]
Hey there 😃 
You're absolutely right! I can provide a quick fix for that one today 😃

**Comment by clawfire** [comment]
Would you prefer to have both native scripts + latin alphabet ? 
I'm thinking about the day to day usage, where native script may be also necessary.

**Comment by cfanoulis** [comment]
The EUDCC is mostly used as a travel document so I feel like just having the latin form is sufficient

**Comment by clawfire** [comment]
ok I think I have something.
I'm testing the firstname and lastname for variation with the latin version included.
If there's a variation, I add the non-latin and latin version to the pass. Seems you're not using the pass in Greece for national identification but in other countries like France or Luxembourg we are using it even to go to restaurant or grocery stores 🤷🏼‍♂️

**Comment by cfanoulis** [comment]
Yeah so do we :p But most people are accustomed with seeing the english version so it's fine lol (our verifier app shows the name both ways anyway)

**Comment by nckbgov** [comment]
Hi,
Thanks for working on the feature to add both versions - latin and non-latin.
Has it been pushed to https://covid19passbook.netlify.app/ ?
I've just generated a new pkpass but I only see Cyrillic.
Thanks!

**Comment by clawfire** [comment]
No yet.
I found out Apple is not following its own standard (lol) and don't allow to display two "main" information under each other so I cannot have the names in the two alphabets on the same area. 

What I did is to use latin alphabet on front of the card and non-latin alphabet on the back of the card if needed for the user.

Will be on the next release this week 😃
