### ISSUE TITLE
[BUG] No English Name for bulgarian citizens and no dates of vaccination

### ISSUE THREAD

**Issue by angelgenkov** [clawfire/covid19-passbook-generator#70]
So, the app does not generate a wallet record with english names and therefore renders it useless. I am from bulgaria and my names are in Bulgaria. Neither at the Bulgarian Airport or any other this has worked. Please add so we can change the language of the entry. Also the wallet record does not show when I was vaccinated. Ita just an empty line.

**Comment by clawfire** [comment]
hi @angelgenkov 😃 
I pushed an update few days ago to support latin and non latin names just for this. 
Plus vaccine date works with more than 20k passes generated now. 

Would you be comfortable to send me to hello@thibaultmilan.com your QR code so I can inspect it? Already had many badly formated QR codes from Ireland, Italy and Spain sadly :(

**Comment by angelgenkov** [comment]
Sent you an e-mail. :)

Thank you!

**Comment by clawfire** [comment]
Got it, will investigate in the upcoming days

**Comment by clawfire** [comment]
Will be fixed in the next release 😃

**Comment by angelgenkov** [comment]
Great! Thank you very much! :)
