### ISSUE TITLE
[feature request] Add German Version

### ISSUE THREAD

**Issue by MentalGear** [clawfire/covid19-passbook-generator#71]
### Is your feature request related to a problem? Please describe.

Thx for this app. Could you add the german version as well to your intro page?

### Describe the solution you'd like

Add the german version, it's compatible with the EU certificate.

**Comment by clawfire** [comment]
The app works with any EU pass (and CH and UK). It's not limited to what you see in the FAQ. The FAQ is here just to tell people where to get their qrcode if they don't have it yet. And I don't know how to get it in Germany so 🤷🏼

**Comment by clawfire** [comment]
But if you tell me how Germans are supposed to get their QRcode, I can add it in the FAQ 😃
