### ISSUE TITLE
[feature request] Add Portugal information on the website

### ISSUE THREAD

**Issue by webdados** [clawfire/covid19-passbook-generator#72]
### Contact Details

marcoalmeida at webdados dot pt

### Describe the solution you'd like

Please add the information on how to get the Portuguese certificate:

1. Trough the "SNS 24" website: https://www.sns24.gov.pt/certificado-digital-covid/
or
2. Trough the "SNS 24" app (ios and android)

**Comment by clawfire** [comment]
OMG 😍  thank you for sharing this with me. I'll add it for sure!

**Comment by webdados** [comment]
I can do a PR on index.html if you prefer it that way.

**Comment by clawfire** [comment]
Would be great. Would save me time. Please pay attention to do the pr from the develop branch ;)

**Comment by webdados** [comment]
Done: https://github.com/clawfire/covid19-passbook-generator/pull/76

Please ignore: https://github.com/clawfire/covid19-passbook-generator/pull/75 (wrong branch)

**Comment by clawfire** [comment]
Thanks 😃 
Merged !

**Comment by webdados** [comment]
BAM!
