### ISSUE TITLE
[BUG] Fornames and Surnames Transposed

### ISSUE THREAD

**Issue by sfeary** [clawfire/covid19-passbook-generator#73]
### What happened?

Hi, thank you for this great service! Not sure if it's a major issue but the digital certificate generated by the web app transposes the surnames and firstnames of the covid certificate issued in Ireland. On our certs the name is structured: Lastname(s), Firstname(s). 

When the certificate for passbook is created the certificate has our surname and firstnames in the wrong order: Firstnames(s) Lastnames(s). 

As i said I'm not sure it's an issue when someone looks at it to scan it but I know it's an issue with other documents in the airport if the name was slightly off.

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
oh I see. Maybe I was a lil bit sleepy when I did that part. Will double-check for sure 😃

**Comment by n00d1e5** [comment]
I have the same issue. -> LUX certificate.

**Comment by clawfire** [comment]
Oh yeah it's for every certificate or nothing 😂 

I'll try to fix that on the upcoming days ☺️

**Comment by n00d1e5** [comment]
> Oh yeah it's for every certificate or nothing 😂
> 
> I'll try to fix that on the upcoming days ☺️

Please check the [PR#78](https://github.com/clawfire/covid19-passbook-generator/pull/78) :)
