### ISSUE TITLE
[BUG] Name is in Greek not Latin

### ISSUE THREAD

**Issue by greatvc** [clawfire/covid19-passbook-generator#79]
### What happened?

Hi, just got my EU vaccination card and i'm happy! (yes i'm pro vacc). So i tried some suggested Wallet apps that enter the certificate in the wallet like 

https://app.getcovidpass.eu/
https://covidpass.marvinsextro.de/

but all of them are saying my QR is not valid. With the official Greek App that we have here the QR is scanned correctly.
From your site i manage to import it fine on the wallet and apple watch! and scanned perfectly !!! so many thanks for that !!!!!!!

I do not know if this is normal but the EU digital template on the wallet says:
SURNAMES & FORENAMES
below it has my First Name in Greek and Last Name in Greek.
Should be the name in Latin, there is on the actual certificate printed correctly and displayed as how i'm i suppose to travel in another country :)
Also it should be inverted, since SURNAMES => my surname first & FORENAMES => my first name second.

many thanks.
-Vassilis

### What browsers are you seeing the problem on?

Chrome

### Are you browsing using

a computer

**Comment by clawfire** [comment]
Hey there 😃 
This bug of first names and last names inverted has already been spotted here #73 and a fix is on his way #78 to be validated 😃 

For your names in non-Latin instead of Latin, it should be both actually. Some countries may require a pass on daily life (like in Luxembourg or France) and I thought having both in the case, it's using non-Latin alphabet would be better.  

But you say It doesn't work and just displays your names in greek?

**Comment by greatvc** [comment]
Thanks for the quick reply.

Happy to see that their first name and last name inverted is already fixed and waiting The rollout.

In Greece, we have a local certificate with a QR code that we can use so it doesn’t matter if that the EU is in latin.

But yes what I’m saying is not both names are displayed I have only my Greek name and not the latin one I prefer to have the Latin one as this is what I’m using for travel and it’s on my passport.


On 22 Jul 2021, at 19:32, Thibault Milan ***@***.***> wrote:

﻿

Hey there 😃
This bug of first names and last names inverted has already been spotted here #73<https://github.com/clawfire/covid19-passbook-generator/issues/73> and a fix is on his way #78<https://github.com/clawfire/covid19-passbook-generator/pull/78> to be validated 😃

For your names in non-Latin instead of Latin, it should be both actually. Some countries may require a pass on daily life (like in Luxembourg or France) and I thought having both in the case, it's using non-Latin alphabet would be better.

But you say It doesn't work and just displays your names in greek?

**Comment by clawfire** [comment]
I just checked and ... well I should get more sleep it seems 😃 
Fixed the condition for the latin addition.

**Comment by clawfire** [comment]
Should be fixed in the next release
