### ISSUE TITLE
[BUG] Capture doesn't work

### ISSUE THREAD

**Issue by clawfire** [clawfire/covid19-passbook-generator#8]
**Describe the bug**
On some iPhone, capture is slow to respond or doesn't work at all

**Smartphone (please complete the following information):**
 - Device: iPhone11, iPhone12
 - OS: iOS 14.6
 - Browser: Safari, Firefox iOS

**Comment by biou** [comment]
J'ai essayé sur un iPhone 12, quand les conditions de luminosité sont correctes, c'est direct (moins d'1 seconde). Le soir avec un éclairage limité c'est plus difficile.

Avec un iPhone 8+ dans des conditions de luminosité correctes, j'arrive à scanner en 2-3 secondes.

iOS 14.6 dans les deux cas. 

Firefox iOS ne fonctionne pas par contre. Le scan se fait mais pas de popup pour le téléchargement du passbook.

**Comment by clawfire** [comment]
Je pense que les réglages par défaut de la lib font qu'elle ne "cherche" que dans ½ de la hauteur et ½ de la largeur, centrée sur la zone video. On doit pouvoir poussé cela à 100% j'imagine.

L'autre solution est de mettre un guide.
