### ISSUE TITLE
[BUG] I can't scan my Code

### ISSUE THREAD

**Issue by mossie29** [clawfire/covid19-passbook-generator#86]
### What happened?

I cant scan my COVID QR code

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hi here 😃 
Have you tried the different points in the FAQ? 

1. Have a good light source and align your QR code with the scan zone edge.
2. The size of the visual aid is the size of the code we need.
3. Your code must be flat (wrinkled paper won’t work well).
4. If you have a screenshot or a picture of your code, you can use the “Import picture” button.
5. Please be sure to use the EU version of your certificate.

**Comment by mossie29** [comment]
All of these things are fine and correct.. and there is no import picture button to be seen, which is why I’ve emailed 😅

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by clawfire** [comment]
Really? Can you screenshot me the page? 
Should be just below the big blue button
![Capture d’écran 2021-07-24 à 11 26 55](https://user-images.githubusercontent.com/1178/126864247-7c432a6c-b22c-47f2-adb7-54deaf69e3c0.png)
