### ISSUE TITLE
[feature request] Add version number on the site

### ISSUE THREAD

**Issue by clawfire** [clawfire/covid19-passbook-generator#87]
### Is your feature request related to a problem? Please describe.

People don't know if the site had a new deployment or not. They are not following me on social media and tags on the GitHub repo are a bit ... techy. 

### Describe the solution you'd like

Display at the very least the version number on the webpage (can be in the footer). 
Consider using the deployment env variable from Netlify for the build date or something like this.
A link to the changelog can be nice too.

**Comment by greatvc** [comment]
Just a version number that will be on the bottom of the site and will match the release version of GitHub think will do it.
Don't over think this, we need your brain for more than that 😄 

And now i DO follow you on twitter!
