### ISSUE TITLE
[BUG] Flash button doesn't work

### ISSUE THREAD

**Issue by clawfire** [clawfire/covid19-passbook-generator#9]
**Describe the bug**
When scanning, the flash button is never enabled

**Expected behavior**
Flash button going responsive and allow to turn on/off the flashlight

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS 14.6
 - Browser Safari

**Comment by biou** [comment]
It seems that the required API is not available in Safari iOS
https://github.com/zxing-js/browser/issues/12

**Comment by clawfire** [comment]
That sucks :(

**Comment by clawfire** [comment]
We should then have a default state "torch control unavailable" which changes to "switch torch on/off" when torch API is available I think.
