### ISSUE TITLE
[BUG] QR code not readed

### ISSUE THREAD

**Issue by Katiechis123** [clawfire/covid19-passbook-generator#93]
### Contact Details

Katiechis@hotmail.com

### What happened?

My QR code for my covid vaccine passport will not work 

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hi there 😃 
Which country issues the QR code? 
Are you trying to scan the code on paper or on-screen?
