### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Clcives** [clawfire/covid19-passbook-generator#98]
### Contact Details

Tinatighe@gmail.com

### What happened?

I am trying to upload my run digital covid verities my wallet on my iPhone but it doesn’t seem to want to? 

### What browsers are you seeing the problem on?

Safari

### Are you browsing using

an iPhone

**Comment by clawfire** [comment]
Hey @Clcives 
Can you be a little bit more specific? Pressing the button lets you choose the file and then a bug happens or you don't even ask to select a file?
